# Generated by Django 5.2.15 on 2026-07-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="calories",
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(default="Main Course", max_length=100),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="gst",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_bestseller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_chef_special",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="prep_time",
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="spice_level",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="veg_nonveg",
            field=models.CharField(default="non-veg", max_length=20),
        ),
    ]
