# Generated by Django 5.2.15 on 2026-07-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_order_orderitem"),
        ("reservation", "0003_alter_reservation_status_alter_table_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("dine_in", "Dine-In"),
                    ("takeaway", "Takeaway"),
                    ("delivery", "Delivery"),
                ],
                default="dine_in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="reservation.reservation",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="reservation.table",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("picked_up", "Picked Up"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="received",
                max_length=20,
            ),
        ),
    ]
