# Generated by Django 5.2.15 on 2026-07-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_order_waiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="item_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="kitchen_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="special_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="waiter_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
