# Generated by Django 5.2.15 on 2026-07-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_orderitem_item_discount_orderitem_kitchen_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="course",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("main_course", "Main Course"),
                    ("dessert", "Dessert"),
                    ("beverage", "Beverage"),
                ],
                default="main_course",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="modifiers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
