# Generated by Django 5.2.15 on 2026-07-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_orderitem_course_orderitem_modifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="waiter_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
