# Generated by Django 5.2.15 on 2026-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_order_waiter_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="kitchen_station",
            field=models.CharField(default="Main Kitchen", max_length=100),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
