# Generated by Django 5.2.15 on 2026-07-19 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_branch_status"),
        ("inventory", "0009_menuitem_barcode_menuitem_is_available_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStockRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opening_stock",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "purchased_stock",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "closing_stock",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "consumption",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("opening_date", models.DateField()),
                ("closing_date", models.DateField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stock_records",
                        to="core.branch",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opening_date", "ingredient__name"],
                "unique_together": {("branch", "ingredient", "opening_date")},
            },
        ),
    ]
