# Generated by Django 5.2.15 on 2026-07-05 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_branch_geofence_radius"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("content_html", models.TextField()),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("all", "All Customers"),
                            ("vip", "VIP Guests Only"),
                            ("frequent", "Frequent Diners (3+ visits)"),
                            ("inactive", "Inactive (No visit in 30 days)"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=50, null=True)),
                ("sent_count", models.IntegerField(default=0)),
                ("open_count", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("reservation_confirmation", "Reservation Confirmation"),
                            ("reservation_approved", "Reservation Approved"),
                            ("reservation_rejected", "Reservation Rejected"),
                            ("reservation_reminder", "Reservation Reminder"),
                            ("table_ready", "Table Ready"),
                            ("check_in_success", "Check In Success"),
                            ("dining_completed", "Dining Completed / Thank You"),
                            ("feedback_request", "Feedback Request"),
                            ("birthday_wishes", "Birthday Wishes"),
                            ("anniversary_wishes", "Anniversary Wishes"),
                            ("coupon_campaign", "Coupon Campaign"),
                            ("festival_greetings", "Festival Greetings"),
                            ("custom_broadcast", "Custom Broadcast"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body_html", models.TextField()),
                ("body_text", models.TextField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient", models.CharField(max_length=255)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("opened", models.BooleanField(default=False)),
                ("clicked", models.BooleanField(default=False)),
                ("retry_count", models.IntegerField(default=0)),
                ("sent_time", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communication_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_app_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationChannelSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("smtp_host", models.CharField(default="localhost", max_length=255)),
                ("smtp_port", models.IntegerField(default=1025)),
                (
                    "smtp_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("smtp_use_tls", models.BooleanField(default=False)),
                ("smtp_use_ssl", models.BooleanField(default=False)),
                (
                    "smtp_sender_name",
                    models.CharField(default="DineIn AI", max_length=255),
                ),
                (
                    "smtp_reply_email",
                    models.EmailField(default="no-reply@dinein.com", max_length=254),
                ),
                (
                    "sms_provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("messagebird", "MessageBird"),
                            ("vonage", "Vonage"),
                            ("fast2sms", "Fast2SMS"),
                            ("msg91", "MSG91"),
                        ],
                        default="twilio",
                        max_length=50,
                    ),
                ),
                (
                    "sms_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sms_api_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sms_sender_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "whatsapp_meta_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "whatsapp_phone_number_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "whatsapp_business_account_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("firebase_credentials_json", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_settings",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
