# Generated by Django 5.2.15 on 2026-07-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationlog",
            name="smtp_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="communicationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
