# Generated by Django 5.2.15 on 2026-07-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_communicationlog_smtp_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="gateway_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="gateway_timeout",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="gateway_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="notificationchannelsettings",
            name="sms_provider",
            field=models.CharField(
                choices=[
                    ("demo", "Demo"),
                    ("android_gateway", "Android SMS Gateway"),
                    ("disabled", "Disabled"),
                ],
                default="demo",
                max_length=50,
            ),
        ),
    ]
