# Generated by Django 5.2.15 on 2026-07-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationchannelsettings_gateway_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationchannelsettings",
            name="sms_provider",
            field=models.CharField(
                choices=[
                    ("demo", "Demo"),
                    ("android_gateway", "Android SMS Gateway"),
                    ("disabled", "Disabled"),
                    ("twilio", "Twilio"),
                    ("messagebird", "MessageBird"),
                    ("vonage", "Vonage"),
                    ("fast2sms", "Fast2SMS"),
                    ("msg91", "MSG91"),
                ],
                default="demo",
                max_length=50,
            ),
        ),
    ]
