# Generated by Django 5.2.15 on 2026-07-20 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_branch_status"),
        ("notifications", "0005_inappnotification_branch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="is_system",
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communication_logs",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="gateway_response_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="gateway_response_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="provider",
            field=models.CharField(default="android_gateway", max_length=50),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="response_time_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="template_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_comm_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="gateway_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="gateway_last_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="gateway_last_status",
            field=models.CharField(default="online", max_length=20),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="gateway_last_tested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="gateway_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_comm_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("body_template", models.TextField()),
                ("placeholders_list", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_templates",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
