# Generated by Django 5.2.15 on 2026-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_communicationlog_template_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationlog",
            name="api_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="delivery_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
