# Generated by Django 5.2.15 on 2026-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_communicationlog_api_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationchannelsettings",
            name="whatsapp_recipient_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
