# Generated by Django 5.2.15 on 2026-07-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_notificationchannelsettings_whatsapp_recipient_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationlog",
            name="reservation_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
