# Generated by Django 5.2.15 on 2026-07-03 13:49

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guest_name", models.CharField(max_length=150)),
                (
                    "guest_phone",
                    models.CharField(
                        max_length=20,
                        validators=[apps.core.validators.validate_phone_number],
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("party_size", models.PositiveIntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("seated", "Seated"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_walk_in", models.BooleanField(default=False)),
                ("is_birthday", models.BooleanField(default=False)),
                ("is_anniversary", models.BooleanField(default=False)),
                ("is_vip", models.BooleanField(default=False)),
                ("needs_wheelchair", models.BooleanField(default=False)),
                ("needs_baby_chair", models.BooleanField(default=False)),
                ("allergy_notes", models.TextField(blank=True, null=True)),
                ("special_requests", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="core.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=20)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("occupied", "Occupied"),
                            ("out_of_service", "Out of Service"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("round", "Round"),
                            ("square", "Square"),
                            ("rectangle", "Rectangle"),
                        ],
                        default="square",
                        max_length=20,
                    ),
                ),
                ("x_coord", models.IntegerField(default=0)),
                ("y_coord", models.IntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="core.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_tables",
                        to="reservation.reservation",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_tables",
                        to="reservation.table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guest_name", models.CharField(max_length=150)),
                (
                    "guest_phone",
                    models.CharField(
                        max_length=20,
                        validators=[apps.core.validators.validate_phone_number],
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("party_size", models.PositiveIntegerField()),
                ("position", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("notified", "Notified"),
                            ("expired", "Expired"),
                            ("checked_in", "Checked In"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=25,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_wait_minutes", models.IntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlists",
                        to="core.branch",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["branch", "start_time", "status"],
                name="reservation_branch__2680a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["guest_phone"], name="reservation_guest_p_ec97e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["guest_name"], name="reservation_guest_n_ea4533_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="reservation_status_af75b6_idx"),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="check_end_time_gt_start_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(("party_size__gt", 0)),
                name="check_party_size_gt_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["branch", "status"], name="reservation_branch__da7db5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["capacity"], name="reservation_capacit_3fa3ac_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("branch", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="reservationtable",
            unique_together={("reservation", "table")},
        ),
        migrations.AddIndex(
            model_name="waitlist",
            index=models.Index(
                fields=["branch", "status", "joined_at"],
                name="reservation_branch__e00a03_idx",
            ),
        ),
    ]
