# Generated by Django 5.2.15 on 2026-07-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_reservation_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("reminder_sent", "Reminder Sent"),
                    ("checked_in", "Checked In"),
                    ("arrived", "Arrived"),
                    ("seated", "Seated"),
                    ("dining", "Dining"),
                    ("checkout_requested", "Checkout Requested"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                    ("no_show", "No Show"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("occupied", "Occupied"),
                    ("cleaning", "Cleaning"),
                    ("out_of_service", "Out of Service"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
