# Generated by Django 5.2.15 on 2026-07-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_branch_status"),
        ("staff", "0003_holidaycalendar_employeebreak"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="staff.employee",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddField(
            model_name="designation",
            name="approval_authority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="designation",
            name="hierarchy_level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="designation",
            name="salary_grade_max",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="designation",
            name="salary_grade_min",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
