# Generated by Django 5.2.15 on 2026-07-23 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_department_branch_department_budget_department_head_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="break_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="late_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendances",
                to="staff.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="working_hours",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="schedule",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_schedules",
                to="staff.employee",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="break_minutes",
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name="EmployeeAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available_from", models.DateField()),
                ("available_to", models.DateField()),
                ("status", models.CharField(default="available", max_length=20)),
                ("remarks", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="staff.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayrollSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.CharField(max_length=7)),
                ("working_days", models.IntegerField(default=0)),
                (
                    "working_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("leave_days", models.IntegerField(default=0)),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_summaries",
                        to="staff.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
