# Generated by Django 5.2.15 on 2026-07-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="geofence_radius",
            field=models.IntegerField(default=100),
        ),
    ]
