# Generated by Django 5.2.15 on 2026-07-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_branch_geofence_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
