# Generated by Django 5.2.15 on 2026-07-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_invoice"),
        ("inventory", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="inventory.order",
            ),
        ),
    ]
