# Generated by Django 5.2.15 on 2026-07-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_invoice_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_cloud_kitchen",
            field=models.BooleanField(default=False),
        ),
    ]
