# Generated by Django 5.2.15 on 2026-07-12 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_branch_is_cloud_kitchen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="branch_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="business_hours",
            field=models.CharField(
                blank=True, default="09:00 AM - 11:00 PM", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="delivery_radius",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="branch",
            name="gst_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="kitchen_type",
            field=models.CharField(default="Dine-in & Takeaway", max_length=100),
        ),
        migrations.AddField(
            model_name="branch",
            name="tax_percentage",
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
