# Generated by Django 5.2.15 on 2026-07-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_branch_branch_manager_branch_business_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
