# Generated by Django 5.2.15 on 2026-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_invoice_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="tax_percentage",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
