# Generated by Django 5.2.15 on 2026-07-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_invoice_cashier_invoice_payment_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="branch",
            name="invoice_prefix",
            field=models.CharField(default="INV", max_length=20),
        ),
        migrations.AddField(
            model_name="branch",
            name="invoice_sequence",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="branch",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="receipt_footer",
            field=models.TextField(
                blank=True,
                default="Thank you for dining with us! Please scan the QR code to review your experience.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="service_charge_percentage",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="branch",
            name="tax_rules",
            field=models.CharField(default="inclusive", max_length=255),
        ),
    ]
