# Generated by Django 5.2.15 on 2026-07-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_invoice_payment_method_alter_invoice_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="waiter_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
