# Generated by Django 5.2.15 on 2026-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_invoice_waiter_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("busy", "Busy"),
                    ("maintenance", "Maintenance"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
