# Generated by Django 4.2.30 on 2026-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_branch_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
    ]
