# Generated by Django 5.2.15 on 2026-07-04 06:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_branch_geofence_radius"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentKeyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(max_length=255, unique=True)),
                (
                    "sentiment_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TopicCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Topic Categories",
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recommendation_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "impact_score",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(default="Anonymous", max_length=255)),
                (
                    "author_avatar_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Portal"),
                            ("google_maps", "Google Maps"),
                            ("yelp", "Yelp"),
                            ("tripadvisor", "TripAdvisor"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("visit_date", models.DateField(blank=True, null=True)),
                (
                    "external_review_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_analyzed", models.BooleanField(default=False)),
                ("priority_score", models.FloatField(default=0.0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu_items",
                    models.ManyToManyField(
                        blank=True, related_name="reviews", to="inventory.menuitem"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReputationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("reputation_score", models.FloatField(default=0.0)),
                ("rating_avg", models.FloatField(default=0.0)),
                ("sentiment_index", models.FloatField(default=0.0)),
                ("nps_score", models.FloatField(default=0.0)),
                ("total_reviews", models.IntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_snapshots",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.URLField(max_length=500)),
                ("file_type", models.CharField(default="image", max_length=50)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="feedback.customerreview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response_text", models.TextField()),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="feedback.customerreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=15,
                    ),
                ),
                ("sentiment_score", models.FloatField(default=0.0)),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("Happy", "Happy"),
                            ("Angry", "Angry"),
                            ("Frustrated", "Frustrated"),
                            ("Disappointed", "Disappointed"),
                            ("Excited", "Excited"),
                            ("Neutral", "Neutral"),
                        ],
                        default="Neutral",
                        max_length=20,
                    ),
                ),
                ("positive_keywords", models.JSONField(blank=True, default=list)),
                ("negative_keywords", models.JSONField(blank=True, default=list)),
                ("suggested_improvements", models.TextField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("manager_action_items", models.JSONField(blank=True, default=list)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight",
                        to="feedback.customerreview",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="insights", to="feedback.topiccategory"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="customerreview",
            index=models.Index(
                fields=["branch", "source"], name="feedback_cu_branch__37d704_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreview",
            index=models.Index(fields=["rating"], name="feedback_cu_rating_62b7bb_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreview",
            index=models.Index(
                fields=["created_at"], name="feedback_cu_created_a3e2c9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reputationsnapshot",
            unique_together={("branch", "date")},
        ),
    ]
