# Generated by Django 5.2.15 on 2026-07-23 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyFeedbackSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("total_reviews", models.IntegerField(default=0)),
                ("positive_reviews", models.IntegerField(default=0)),
                ("neutral_reviews", models.IntegerField(default=0)),
                ("negative_reviews", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("top_category", models.CharField(blank=True, max_length=100)),
                ("trending_metric", models.CharField(blank=True, max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customerreview",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_category", to="feedback.topiccategory"
            ),
        ),
        migrations.AddField(
            model_name="customerreview",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customerreview",
            name="sentiment",
            field=models.CharField(default="neutral", max_length=20),
        ),
    ]
