# Generated by Django 5.2.15 on 2026-07-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_loyaltyprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltyprofile",
            name="tier",
            field=models.CharField(
                choices=[
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                    ("diamond", "Diamond"),
                ],
                default="silver",
                max_length=20,
            ),
        ),
    ]
