# Generated by Django 5.2.15 on 2026-07-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_loyaltyprofile_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
